title: DataScience portfolio
logo: # /assets/img/logo.png
description: Alex Coch<br><br>
  View My Profile on:<br><br>
  <a href=https://linkedin.com/in/alexcoch>LinkedIn</a><br><br>
  <a href=https://kaggle.com/alekscoch>Kaggle</a><br><br>
  <a href=https://facebook.com/f.alex.coch>Facebook</a><br>
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
