title: <p align="center">Alex Coch</p>
logo:  /assets/img/logo.jpg
description: 
  <p align="center">
  <a href=https://linkedin.com/in/alexcoch>LinkedIn</a> |
  <a href=https://kaggle.com/alekscoch>Kaggle</a> |
  <a href=https://facebook.com/f.alex.coch>Facebook</a>
  </p>   
  <a href="#machinelearning">Machine Learning</a><br>
  <a href="#boston">Predicting Boston Housing Prices</a>
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
