title: DataScience portfolio
logo: /assets/img/logo.png
description: 
Alex Coch<br><br>
<a href=https://linkedin.com/in/alexcoch>View My LinkedIn Profile</a><br><br>
<a href=https://kaggle.com/alekscoch>View My Kaggle Profile</a><br><br>
<a href=https://facebook.com/f.alex.coch>View My Facebook Profile</a><br><br>
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
