title: <p align="center">Alex Coch</p>
logo:  /assets/img/logo.jpg
description: 
  <p align="center">
  <a href=https://linkedin.com/in/alexcoch>LinkedIn</a> |
  <a href=https://kaggle.com/alekscoch>Kaggle</a> |
  <a href=https://facebook.com/f.alex.coch>Facebook</a>
  </p>   
  Machine Learning<br>
  - <a href="#boston">Predicting Boston Housing Prices</a><br>
  - <a href="#donors">Finding Donors for CharityML</a><br>
  - <a href="#segments">Creating Customer Segments</a><br>
  - <a href="#smartcab">Training a Smartcab to Drive</a><br>
  Computer vision<br>
  - <a href="#digit">Digit Sequence Recognition</a><br>
  Natural Language Processing<br>
  - <a href="#message">Message Classifier</a><br>
  - <a href="#sentiment">Sentiment Analysis</a><br>
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
