title: <p align="center">Alex Coch</p>
logo:  /assets/img/logo.png
description: 
  <p align="center">
  <a href=https://linkedin.com/in/alexcoch>LinkedIn</a> |
  <a href=https://kaggle.com/alekscoch>Kaggle</a> |
  <a href=https://facebook.com/f.alex.coch>Facebook</a>
  </p>   
  <p><a href="#bottom">Somewhere</a></p>
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
